version: '3.7'

services:
  # ################################################################################
  # Database
  # ################################################################################
  postgres:
    image: postgres:13
    container_name: approval-system-postgres-1
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -t 5 -U backend_user || false"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=approval_dev
      - POSTGRES_USER=approval_user
      - POSTGRES_PASSWORD=approval
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

